package master_provider_else.reclamos.domain.model

import master_provider_else.reclamos.data.database.entity.ReclamoEntity

data class Claim(
  val codigoEstadoReclamo:String,
  val nombreClaseReclamo:String,
  val codigoReclamo:String,
  val nombreSuministro:String,
  val direccionElectrica:String,
  val codigoSuministro:String,
  val descripcionReclamo:String,
  val referenciaUbicacion:String,
  val codigoRutaSuministro:String,
  val codigoSED:String,
  val datoMCo:String,
  val celular:String,
  val codigoDireccionElectrica:String,
  val fechaRegistro:String,
  val plazo:String,
  val sectorTipico:String,
  val fechaLimiteAtencion:String,
  val latitud:String,
  val longitud:String,
  val fechaProgramacion:Long,
  val fechaEnCamino:Long,
  val fechaEjecucionInicio:Long,
  val fechaEjecucionFin:Long,
  val tipoReclamo:String,
  val enviado:Int,
  val tipolistaReclamo:String,
)

fun ReclamoEntity.toDomain() = Claim(
  codigoEstadoReclamo,
      nombreClaseReclamo,
      codigoReclamo,
      nombreSuministro,
      direccionElectrica,
      codigoSuministro,
      descripcionReclamo,
      referenciaUbicacion,
      codigoRutaSuministro,
      codigoSED,
      datoMCo,
      celular,
      codigoDireccionElectrica,
      fechaRegistro,
      plazo,
      sectorTipico,
      fechaLimiteAtencion,
      latitud,
      longitud,
      fechaProgramacion,
      fechaEnCamino,
      fechaEjecucionInicio,
      fechaEjecucionFin,
      tipoReclamo,
      enviado,
      tipolistaReclamo
)
